### ISSUE TITLE
Create Persona and User Story for Users

### ISSUE THREAD

**Issue by cburakaygun** [bounswe/bounswe2018group7#26]
Create a Persona, some User Stories and Acceptance Criteria for a **user** (registered). Write your work in a comment under this Issue so that we can give you some feedbacks. Following templates should be followed:

**Persona**
* A Picture  (can be ignored here)
* Some Details
* A General Goal

**User Story**
As a user, `person name` can `what` so that `why`.

**Acceptance Criteria**
* Item 1
* Item 2
* ...

**Comment by jediinthehouse** [comment]
## Persona Description: 
*  Muzaffer YILMAZ is a retired man born in sivas but currently living in İstanbul. Since he is not going to Sivas very often he likes to tag every detail reminds him his hometown, Sivas.Like all old people, he likes to live in his memories and enjoys thinking about the past.
He has two kids and three grandkids. He is a great dog lover, knows lots of things about raising dogs and taking care of them. He has lots of photos of the old times of İstanbul which belongs to his teenagehood and older photos of Sivas, from his childhood. 
	Since he has a lot of free time he likes to spend a lot of time online, or outside, taking photos and exploring new places and areas.

### User Story

* As an old man who has lots of memories and photos about the past years of Istanbul and Sivas, he can share his old photos and their stories in a memory post and tag them into the map in his profile, So that he can share the world he grew up once with other people, especially younger, like his grandkids and their friends. 

* A man who loves dogs and likes to share his knowledge, he can share useful info about dogs and how dog breeds changes over time in his posts and learn more about dogs by searching via dog tags for example. So that he can help others about raising dogs and give brief information about dog related places in the city, and the dog breeds in the city.

* A man who loves to share the things reminds him his young ages. He can search for the past tags of the places and events he has been in when he was younger, with names and tags. So he can enjoy re-living his memories through hi-story app.
A man who likes to wander around and explore new places. He can see his recommended places and make a daily exploring route so that he can see hidden new places and the things which might be better for his interests.

### Acceptance Criteria:

* He wants no unrelated posts in the application.
* He wants his profile is secure 
* He wants his personal information is not be able to used by a third party without his consent
* He wants to post new items.
* He wants to comment, like, annotate new items.

![https://raw.githubusercontent.com/bounswe/bounswe2018group7/master/docs/user.png.png]

**Comment by abcdrk** [comment]
The cartoon is awesome 😄😄 
Just need to decrease the size i think.
Well done 👍

**Comment by cburakaygun** [comment]
Hello @jediinthehouse.
I have some questions about the User Stories.
> he can share his old photos and their stories in a memory post and tag them into the map in his profile

I don't think there is such a thing as "tagging stories in the map in the profile". As far as I know, there are two maps in our application: 
* `Main Map`: Resides on Homepage and displays all the Memory Posts in the system over related locations.
* `Memory Map`: Redies in a Memory Post and displays the location of the Memory Post.

Both of these maps are driven by the system. Users do not add elements to the maps. Users specify a Memory Location while creating a Memory Post, then the system creates a Memory Map and sets it to the Memory Location user has given. Also, the system updates the Main Map and adds an indicator for the Memory Post user has created over the Memory Location user has given.

Please correct me if I am wrong.

> he can search for the past tags of the places and events he has been to when he was younger, with names and tags

This sentence is a bit weird. What do you mean by "searching for the past tags with tags"? Also, what is a "past tag"?
