### ISSUE TITLE
Create Persona and User Story for Admins

### ISSUE THREAD

**Issue by cburakaygun** [bounswe/bounswe2018group7#27]
Create a Persona, some User Stories and Acceptance Criteria for an **admin**. Write your work in a comment under this Issue so that we can give you some feedbacks. Following templates should be followed:

**Persona**
* A Picture  (can be ignored here)
* Some Details
* A General Goal

**User Story**
As an admin, `person name` can `what` so that `why`.

**Acceptance Criteria**
* Item 1
* Item 2
* ...

**Comment by serdarada** [comment]
**PERSONA**

David Anderson from UK.
Age :23, Single.

He is a master's student in Boğaziçi University Computer Engineering department,lives in Istanbul.
He loves walking at Bebek coast around midnight.

He speaks Turkish as secondary language fluently and he is pre-intermediate level Spanish and French speaker..

He is a team player who can be a part of big software projects and he is interested in back-end development.

He wants to build an IT company in a few years, so working with "hi story" he aims to gain some experience and money. 

He connects to the platform everyday between 5PM and 7PM.






**USER STORY**

As an admin, David can start the system maintanence so that there will be minimal data loss on a server crash.

As an admin, David can delete some memory items so that he can prevent spamming.

As an admin, David can ban some users for some time(we can delete that part if we don't rant to implement it)/delete some comments so that he can prevent offensive language or racism.



**ACCEPTANCE CRITERIA**

* System shall provide deleting memory items.
* System shall provide deleting comments.
  
![david anderson](https://user-images.githubusercontent.com/14983171/36913805-21a362b0-1e5c-11e8-91c0-9300fa041b46.png)
