### ISSUE TITLE
Completion of Requirements Version 1

### ISSUE THREAD

**Issue by cburakaygun** [bounswe/bounswe2018group7#37]
Today requirements were revised at the [meeting](https://github.com/bounswe/bounswe2018group7/wiki/Meeting-%235). Update [requirements](https://github.com/bounswe/bounswe2018group7/wiki/Requirements) accordingly and also make additional changes as necessary in order to complete Version 1.

**Comment by cburakaygun** [comment]
Hello team!
I updated our [Requirements Version 1](https://github.com/bounswe/bounswe2018group7/wiki/Requirements) as we discussed in the meeting yesterday. Maybe you want to take a look at it.
@abcdrk @eneskosr @fakeisback @ferhatmelih @jediinthehouse @ramazanarslan @serdarada

**Comment by serdarada** [comment]
Nice work!

I have a few questions.

Item `1.1.3.1.5` says `Users shall be able to see the memory posts liked by the other users on profile.`  but I believe we decided that, users can see what memory posts they liked in their profile, but other users can only see the memory posts created by them.
Maybe we can add a subsection under `1.1.3` about what users can see in their own profile page.

Under the section `1.1.4 Memory post` there are items about comments, I think we can move them to section `1.1.5 Comment` or we can move `1.1.5` under the `1.1.4` and merge their related parts.
Because in the current version there is ambiguity where an item about comments can be placed under. `1.1.4.6` and `1.1.5.2` are duplicates which are created by this ambiguity.

I think `Users shall be able to delete any annotations from their memory posts` as well as comments. We can add this as `1.1.6.5`.

**Comment by cburakaygun** [comment]
@serdarada Thanks for quick feedback. I think you are right about all of the situations you mentioned. So,
* I deleted `1.1.3.1.5 - Users shall be able to see the memory posts liked by the other users on profile.`
* I moved requirements about comments from `1.1.4 Memory Post` to `1.1.5 Comment`
* I added `1.1.6.5 - Users shall be able to delete any annotations in their memory posts.`

**Comment by eneskosr** [comment]
I have a few discussions.

- `1.1.7 `Users can search within the memory title and memory story as we have talked in the meeting.  
- `1.2` Guest users can see only the main page and main page for a guest user contains only Top 10 (changeable) popular or recently posted memory items. 
- `1.3.7` In this section, you can specify that when viewing another profile the user can only see the memory items posted, not the information of the profile. 
- `1.3.9.4` Can all users see the dislike count? Instead of doing that, we can have one attribute for like count and +1 for like and -1 for dislike in my opinion.
- `1.3.10.2 and 1.3.10.4` The lower limit for these items can be deleted. 500 characters is too much for a lower limit for memory item. Also, titles can be shorter than 10 characters. 
- `1.3.15` Comments can contain media; picture, audio, video.
- `1.1.4.2` For a memory post, only memory title and memory story should be compulsory. User may not remember the time or location.

You have almost changed every item and now they look decent. Thanks for your effort.

**Comment by cburakaygun** [comment]
@eneskosr I guess, you took a really close look at the requirements. :)

> `1.1.7 `Users can search within the memory title and memory story as we have talked in the meeting.  

What I have in mind is that when a user writes some keywords in search bar and clicks search button, the system will search those keywords in memory titles and memory stories by default. So, users don't have options like "search in memory titles" or "search in memory stories". Maybe we can add this description as a requirement under `1.3`. Or should users have such options? What do you think?

> `1.2` Guest users can see only the main page and main page for a guest user contains only Top 10 (changeable) popular or recently posted memory items. 

We have no definition of `popular` right now. So, it can be _last recent 10 memory posts_ maybe. Also, when guests click on a memory post in homepage, can't they see the page of that memory post?

> `1.3.7` In this section, you can specify that when viewing another profile the user can only see the memory items posted, not the information of the profile.

`1.1.3.1` and sub-items state what a user can see on another user's profile. I think, it is redundant to state those under `1.3.7` again.

> `1.3.9.4` Can all users see the dislike count? Instead of doing that, we can have one attribute for like count and +1 for like and -1 for dislike in my opinion.

Can be done. Let's hear about this from our teammates.

> `1.3.10.2 and 1.3.10.4` The lower limit for these items can be deleted. 500 characters is too much for a lower limit for memory item. Also, titles can be shorter than 10 characters. 

I think there should be some lower limits, otherwise it will be possible to create nearly empty memory posts which is not nice. Again, let's hear about this from our teammates.

> `1.3.15` Comments can contain media; picture, audio, video.

As far as I know, details of comments are not specified in project description nor discussed at customer meetings. Also, annotations (which are sort of comments) support media. So, I prefer to keep comment system simple, but can be done.

> `1.1.4.2` For a memory post, only memory title and memory story should be compulsory. User may not remember the time or location.

It says "Users shall **be able to** ..." Hence, no memory items are compulsory right now. I guess you suggest stating compulsion of memory title and memory story as requirements.

We need your opinions @abcdrk @fakeisback @ferhatmelih @jediinthehouse @ramazanarslan @serdarada

**Comment by serdarada** [comment]
`1.1.7` I think the current item is sufficient.

`1.2` I think guests should see 10 recently memory posts and also can see their pages when they click

`1.3.9.4` I think current items are good. 5 like + 5 dislike should be different than 0 like + 0 dislike

`1.3.10.2` and `1.3.10.4` I agree with @eneskosr.  Stories in a memory post may be optional (also as far as I remember our customer said this too in Customer Meeting 1), some title and photo from 1950 taksim tells enough. But if we want to set a lower limit it might be 50 instead of 500,Lower limit for the title seems redundant too. 

`1.3.15` I agree with @cburakaygun, comments should be simple.

**Comment by cburakaygun** [comment]
Based on the discussions of last 3 comments (before this one), I've made the following updates:
* Added `1.3.17 Search` section to specify the following:
  * Searching for Memory Posts will be based on Memory Title, Memory Story and Memory Location.
  * Searching for other users will be based on usernames and real names.
* Revised `1.3.8 Homepage` section to restrict Guests to recent 10 Memory Posts only.
* Deleted minumum and maximum characters contraints from Memory Title (`1.3.10.1`) and Memory Story (`1.3.10.4`)
* Added `1.3.9.7 Memory posts shall be required to have a memory title.` Other sections of a Memory Post optional.
* Comments can contain plain text and links only. (as before)
* Like and Dislike counts are separate. (as before)
