### ISSUE TITLE
Review Android MockUps

### ISSUE THREAD

**Issue by ramazanarslan** [bounswe/bounswe2018group7#39]
We have to review our web and android mock ups. So we change mock up program to Figma.

**Comment by ramazanarslan** [comment]
<img width="244" alt="ekran resmi 2018-03-07 16 38 53" src="https://user-images.githubusercontent.com/31334024/37095182-41379af6-2226-11e8-8850-0792d912ad40.png">
I am confused. Can you help me for this page. 
Under the Search for Post, what components I should  add?

**Comment by cburakaygun** [comment]
Guests should see the followings on home:
* Main Map
* Last recent 10 Memory Posts
* Sign-in and sign-up buttons/regions

Users should see the followings on home:
* Main Map
* Search Bar
* Last Recent Memory Posts
* Recommended Memory Posts (based on current location)
* Recommended Memory Posts (based on user's activity)

I think we haven't discussed the details of Memory Posts shown on home yet.

By the way, we can add comments to the specific parts of mock-ups on Figma. I suggest discussing about the details of mock-ups there, it will be more efficient I think.

**Comment by cburakaygun** [comment]
@ramazanarslan @jediinthehouse I have a suggestion about the Issue. If you have divided the jobs like "one person does Android mock-ups and one person does Web mock-ups", then it would be better to have 2 separate Issues. Since there are some comments about Android on this Issue, this can stay for revising Android Mock-ups and a new Issue can be opened for revising Web mock-ups.
