### ISSUE TITLE
Create Sequence Diagrams for 'Create a Post ' and 'Edit a Post'

### ISSUE THREAD

**Issue by ramazanarslan** [bounswe/bounswe2018group7#48]

**Comment by ramazanarslan** [comment]
I have drawed Edit a Post sequence diagram

https://drive.google.com/file/d/1T1cOZTKIgxShT3HVcCbbL8HZ_hjrbsvx/view?usp=sharing

**Comment by ramazanarslan** [comment]
I have added Create a Post diagram 

https://drive.google.com/file/d/1Tm5FjeWCYdm4uXNW_rpRJo5Fv53lCvDN/view?usp=sharing

**Comment by serdarada** [comment]
@ramazanarslan in the create a post diagram, instead of mtime and mtimedb, there are mlocation and mlocationdb duplicates.

Also, I think the alternate box should not include location and time objects since it is only related to memory post db. And maybe memory post db object can be created after time and location processes are completed

**Comment by ramazanarslan** [comment]
You are right I have forgot to arrange it. Thanks.
